#
# This Makefile was automatically generated by Code::Blocks IDE.
#

SRCS_fd1 = \
preprocess_code.f \
snowmodel_main.f \
dataassim_user.f \
enbal_code.f \
snowpack_code.f \
snowtran_code.f \
micromet_code.f \
outputs_user.f \
readparam_code.f 

OBJS_fd1 = \
preprocess_code.o \
snowmodel_main.o \
dataassim_user.o \
enbal_code.o \
snowpack_code.o \
snowtran_code.o \
micromet_code.o \
outputs_user.o \
readparam_code.o 

SRC_DIR_fd1 = 
OBJS_DIR = SnowModel/
EXE_DIR = SnowModel/

EXE = SnowModel
FC = gfortran
IDIR = 
CFLAGS = -Wall  -J$(OBJS_DIR) $(IDIR)
LFLAGS = 
LIBS = 

VPATH = $(SRC_DIR_fd1):$(OBJS_DIR)
OBJS = $(addprefix $(OBJS_DIR), $(OBJS_fd1))

all : $(EXE)

$(EXE) : $(OBJS_fd1)
	@mkdir -p $(EXE_DIR)
	$(FC) -o $(EXE_DIR)$(EXE) $(OBJS) $(LFLAGS) $(LIBS)

$(OBJS_fd1):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_fd1)$(@:.o=.f) -o $(OBJS_DIR)$@

clean :
	rm -f $(OBJS_DIR)*.*
	rm -f $(EXE_DIR)$(EXE)

# Dependencies of files
preprocess_code.o: \
    preprocess_code.f
snowmodel_main.o: \
    snowmodel_main.f
dataassim_user.o: \
    dataassim_user.f
enbal_code.o: \
    enbal_code.f
snowpack_code.o: \
    snowpack_code.f
snowtran_code.o: \
    snowtran_code.f
micromet_code.o: \
    micromet_code.f
outputs_user.o: \
    outputs_user.f
readparam_code.o: \
    readparam_code.f

