#
# This Makefile was automatically generated by Code::Blocks IDE.
#

SRCS_f95d1 = \
snowpack_code.f95 \
dataassim_user.f95 \
readparam_code.f95 \
enbal_code.f95 \
snowtran_code.f95 \
outputs_user.f95 \
preprocess_code.f95 \
micromet_code.f95 \
snowmodel_main.f95 

OBJS_f95d1 = \
snowpack_code.o \
dataassim_user.o \
readparam_code.o \
enbal_code.o \
snowtran_code.o \
outputs_user.o \
preprocess_code.o \
micromet_code.o \
snowmodel_main.o 

SRC_DIR_f95d1 = 
OBJS_DIR = .objs/
EXE_DIR = 

EXE = SNOWMODEL.exe
FC = mingw32-gfortran.exe
IDIR = 
CFLAGS = -Wall -O2  -J$(OBJS_DIR) $(IDIR)
LFLAGS = -s 
LIBS = 

VPATH = $(SRC_DIR_f95d1):$(OBJS_DIR)
OBJS = $(addprefix $(OBJS_DIR), $(OBJS_f95d1))

all : $(EXE)

$(EXE) : $(OBJS_f95d1)
	@mkdir -p $(EXE_DIR)
	$(FC) -o $(EXE_DIR)$(EXE) $(OBJS) $(LFLAGS) $(LIBS)

$(OBJS_f95d1):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_f95d1)$(@:.o=.f95) -o $(OBJS_DIR)$@

clean :
	rm -f $(OBJS_DIR)*.*
	rm -f $(EXE_DIR)$(EXE)

# Dependencies of files
snowpack_code.o: \
    snowpack_code.f95
dataassim_user.o: \
    dataassim_user.f95
readparam_code.o: \
    readparam_code.f95
enbal_code.o: \
    enbal_code.f95
snowtran_code.o: \
    snowtran_code.f95
outputs_user.o: \
    outputs_user.f95
preprocess_code.o: \
    preprocess_code.f95
micromet_code.o: \
    micromet_code.f95
snowmodel_main.o: \
    snowmodel_main.f95

